/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: 1.bmp
* Dimensions:  28 * 64
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR ac1[] = {
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, __XXXXXX, XXXXXXX_, ________,
  XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXX____,
  XXXXXXXX, XXXXXXXX, XXXX____, XX______,
  XXXXXXXX, XXXXXXXX, _______X, X_______,
  XXXXXXXX, XXXXXXX_, _____XXX, ________,
  XXXXXXXX, XXXXX___, ___XXX__, ________,
  XXXXXXXX, XX_____X, XXXXX___, ________,
  XXXXXXXX, XXXXXXXX, XXXX____, ________,
  XXXXXXXX, XXXXXXXX, XX______, ________,
  XXXXXXXX, XXXXXXXX, ________, ________,
  XXXXXXXX, XXXXXXX_, ________, ________,
  XXXXXXXX, _____XXX, ________, ________,
  XXXXXXXX, ______XX, X_______, ________,
  XXXXXXXX, XXXX___X, X_______, ________,
  XXXXXXXX, XXXXXXXX, XX______, ________,
  XXXXXXXX, _XXXXXX_, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________,
  XXXXXXXX, ________, ________, ________

};

GUI_Bitmap_t bm1 = {
  28, /* XSize */
  64, /* YSize */
  4, /* BytesPerLine */
  1, /* BitsPerPixel */
  ac1,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */

