/***********************************************************************
************************************************************************
**                                                                    **
**       --------------Sparking Bitmap Converter--------------        **
**     Developed for I2C LCD, an easy-to-use display tool for makers. **
**                       Joney.S@foxmail.com                          **
**                                                                    **
************************************************************************
************************************************************************
*
* Code generated by
*
*        Sparking-BitmapConverter v1.0
*        Compiled May 15 2015
*        Sparking Work Speace
*
************************************************************************
*
* Source file: tomb.bmp
* Dimensions:  58 * 64
*
************************************************************************
*/

#include "I2C_LCD.h"


#ifndef GUI_STORAGE_PTR
  #define GUI_STORAGE_PTR PROGMEM
#endif


const unsigned char GUI_STORAGE_PTR actomb[] = {
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, X_XXXXXX, XXXXXXXX, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, X_XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX___XXX, X_XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XX____, __XXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, __XXXXXX, XXXXXXXX, XX______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, X_XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, X_XXXXXX, XXXXXXXX, X_______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, X_XXXXXX, XXXXXXXX, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  XXXXXXXX, XXXXX___, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, XX______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, X_______, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ________, ________, ________

};

GUI_Bitmap_t bmtomb = {
  58, /* XSize */
  64, /* YSize */
  8, /* BytesPerLine */
  1, /* BitsPerPixel */
  actomb,  /* Pointer to picture data (indices) */
};

/* *** End of file *** */

